sudo: required
services:
  - docker

before_install:
  - docker build -t bhush/reactjs -f Dockerfile.dev .

scripts:
  - docker run -e CI=true bhush/reactjs npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-813539611244"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"